# -*- coding: utf-8 -*-
"""actbasic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1437lfgsapgo2XSSfScfNwMWUY-6HBqCO
"""



"""Activation Function:"""

#The input of the activation function is the output from the input times weight + bias. the output of the activaton function becomes the input to the next neuron
# we use activation function for tuning
# step function. y=1 x>0. y=0 if x<=0
# sigmoid: y=1/1+ e^-x
#linear 
# Rectified linear activation function: y=x if x>0. y=0 if x<=0. It produces granular output.

import numpy as np

np.random.seed(0)

X=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

inputs=[0,2,-1,3.3,-2.7,1.1,2.2,-100]

output=[]

#Rectified linear activation function
for i in inputs:
  if i>0:
    output.append(i)
  elif i<=0:
    output.append(0)
print(output)